//! Safe, atomic mutations over one SOKF knowledge tree.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io::Write as _;
use std::path::{Component, Path, PathBuf};

use rmcp::schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use super::bundle::load_bundle;
use super::concept::parse_concept;
use super::graph::Graph;
use crate::error::{Error, Result};
use crate::validate;

/// Who requested a mutation, and therefore which protected fields may move.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MutationPolicy {
    /// Harness and agent callers: identity and verification are immutable.
    AgentSafe,
    /// A deliberate human CLI call: identity and verification may change.
    HumanOverride,
}

// The MCP contract includes these coding-tool-compatible request shapes.
// sokf:begin tools
/// One exact replacement, evaluated against the original file.
#[derive(Debug, Clone, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
#[schemars(crate = "rmcp::schemars")]
pub struct ExactEdit {
    /// Text that must occur exactly once in the original file.
    pub old_text: String,
    /// Text that replaces the matched bytes.
    pub new_text: String,
}

/// The machine request accepted by the edit adapters.
#[derive(Debug, Clone, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
#[schemars(crate = "rmcp::schemars")]
pub struct EditRequest {
    /// Existing concept ID, virtual address, or physical knowledge path.
    pub path: String,
    /// Non-overlapping replacements evaluated against one original file.
    pub edits: Vec<ExactEdit>,
}

/// The machine request accepted by the write adapters.
#[derive(Debug, Clone, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
#[schemars(crate = "rmcp::schemars")]
pub struct WriteRequest {
    /// Existing concept identity, or a physical path for creation.
    pub path: String,
    /// Complete replacement document.
    pub content: String,
}
// sokf:end tools

/// Whether validation could establish the state left on disk.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum ValidationState {
    /// Validation completed without an error finding.
    Valid,
    /// Validation completed and found at least one error.
    Invalid,
    /// Repair or validation could not establish the final state.
    Unknown,
}

/// Which phase produced one filesystem change.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum ChangeSource {
    /// The caller's edit or write.
    Requested,
    /// A change generated by automatic repair.
    Repair,
}

/// A requested or repair-generated file change.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MutationChange {
    /// Knowledge-relative path changed in this phase.
    pub path: String,
    /// Phase that produced the change.
    pub source: ChangeSource,
    /// Unified whole-file diff from the phase's input to output.
    pub diff: String,
}

/// One finding left after repair, or an error that made validation unknown.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct MutationFinding {
    /// `error` or `warning`.
    pub severity: String,
    /// Repository-relative subject, absent for infrastructure failures.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Human-readable finding.
    pub message: String,
}

/// A mutation that was applied, including everything automatic repair changed.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MutationResult {
    /// Always true: precondition failures return an error instead.
    pub applied: bool,
    /// State established after repair.
    pub validation: ValidationState,
    /// Repository-relative physical path selected before mutation.
    pub resolved_path: String,
    /// Repository-relative physical path after automatic refiling.
    pub final_path: String,
    /// Requested and repair-generated changes, in phase and path order.
    pub changes: Vec<MutationChange>,
    /// Remaining validation findings, or why validation is unknown.
    pub findings: Vec<MutationFinding>,
}

pub(super) fn edit(
    bundle_dir: &Path,
    repo_root: &Path,
    request: EditRequest,
    policy: MutationPolicy,
) -> Result<MutationResult> {
    if request.edits.is_empty() {
        return sokf_error("at least one edit is required");
    }
    let path = resolve_existing(bundle_dir, repo_root, &request.path)?;
    let original = read(&path)?;
    let replacement = apply_exact_edits(&original, &request.edits)?;
    if replacement == original {
        return sokf_error("the edit would not change the target");
    }
    check_policy(
        Some(&original),
        &replacement,
        policy,
        is_reserved_index(&path),
    )?;
    apply(bundle_dir, repo_root, path, replacement)
}

pub(super) fn write(
    bundle_dir: &Path,
    repo_root: &Path,
    request: WriteRequest,
    policy: MutationPolicy,
) -> Result<MutationResult> {
    let path = resolve_write_target(bundle_dir, repo_root, &request.path)?;
    let original = if path.exists() {
        Some(read(&path)?)
    } else {
        None
    };
    if original.as_deref() == Some(request.content.as_str()) {
        return sokf_error("the write would not change the target");
    }
    check_policy(
        original.as_deref(),
        &request.content,
        policy,
        is_reserved_index(&path),
    )?;
    apply(bundle_dir, repo_root, path, request.content)
}

fn apply(
    bundle_dir: &Path,
    repo_root: &Path,
    path: PathBuf,
    replacement: String,
) -> Result<MutationResult> {
    let before = snapshot(bundle_dir, repo_root)?;
    atomic_write(&path, &replacement)?;
    let resolved_path = display_path(repo_root, &path);
    // The atomic write changed exactly this path. Build its phase snapshot
    // from known input rather than doing a fallible read after bytes changed.
    let mut after_request = before.clone();
    after_request.insert(resolved_path.clone(), replacement);
    let mut changes = changes_between(&before, &after_request, ChangeSource::Requested);

    let repair = match validate::fix_repo(repo_root, bundle_dir, &[]) {
        Ok(repair) => repair,
        Err(error) => {
            let current = snapshot(bundle_dir, repo_root).unwrap_or_else(|_| after_request.clone());
            changes.extend(changes_between(
                &after_request,
                &current,
                ChangeSource::Repair,
            ));
            return Ok(MutationResult {
                applied: true,
                validation: ValidationState::Unknown,
                resolved_path: resolved_path.clone(),
                final_path: resolved_path,
                changes,
                findings: vec![MutationFinding {
                    severity: "error".into(),
                    path: None,
                    message: format!("automatic repair failed: {error}"),
                }],
            });
        }
    };
    let after_repair = match snapshot(bundle_dir, repo_root) {
        Ok(snapshot) => snapshot,
        Err(error) => {
            return Ok(unknown_result(
                resolved_path.clone(),
                repaired_path(repo_root, &resolved_path, &repair.written),
                changes,
                format!("automatic repair completed but its changes could not be read: {error}"),
            ));
        }
    };
    changes.extend(changes_between(
        &after_request,
        &after_repair,
        ChangeSource::Repair,
    ));
    let final_path = repaired_path(repo_root, &resolved_path, &repair.written);

    let grammar = match validate::schema::load_grammar(repo_root) {
        Ok(grammar) => grammar,
        Err(error) => {
            return Ok(unknown_result(
                resolved_path,
                final_path,
                changes,
                format!("validation could not load its grammar: {error}"),
            ));
        }
    };
    let report = match validate::validate_repo(repo_root, bundle_dir, &[], &grammar) {
        Ok(report) => report.report,
        Err(error) => {
            return Ok(unknown_result(
                resolved_path,
                final_path,
                changes,
                format!("validation failed: {error}"),
            ));
        }
    };
    let validation = if report.passed() {
        ValidationState::Valid
    } else {
        ValidationState::Invalid
    };
    let findings = report
        .findings
        .into_iter()
        .map(|finding| MutationFinding {
            severity: finding.severity().into(),
            path: Some(finding.path),
            message: finding.message,
        })
        .collect();
    Ok(MutationResult {
        applied: true,
        validation,
        resolved_path,
        final_path,
        changes,
        findings,
    })
}

fn unknown_result(
    resolved_path: String,
    final_path: String,
    changes: Vec<MutationChange>,
    message: String,
) -> MutationResult {
    MutationResult {
        applied: true,
        validation: ValidationState::Unknown,
        resolved_path,
        final_path,
        changes,
        findings: vec![MutationFinding {
            severity: "error".into(),
            path: None,
            message,
        }],
    }
}

fn resolve_existing(bundle_dir: &Path, repo_root: &Path, asked: &str) -> Result<PathBuf> {
    reject_section_address(asked)?;
    let target = asked.strip_prefix("sokf:").unwrap_or(asked);
    let bundle = load_bundle(bundle_dir)?;
    let graph = Graph::build(&bundle);
    if let Some(identity) = graph.resolve(target)
        && let Some(concept) = bundle.concepts.iter().find(|concept| {
            concept.id.as_deref() == Some(identity.as_str())
                || (concept.id.is_none() && concept.path == identity)
        })
    {
        return contained(bundle_dir, &bundle.root.join(&concept.path));
    }
    let physical = physical_path(bundle_dir, repo_root, target)?;
    if physical.is_file() {
        if physical
            .file_name()
            .is_some_and(|name| name == "manifest.sokf.yaml")
        {
            return sokf_error("mutation of `manifest.sokf.yaml` is reserved");
        }
        if physical
            .extension()
            .is_none_or(|extension| extension != "md")
        {
            return sokf_error("SOKF mutation targets must be Markdown documents");
        }
        return contained(bundle_dir, &physical);
    }
    sokf_error(format!("unknown SOKF target `{asked}`"))
}

fn resolve_write_target(bundle_dir: &Path, repo_root: &Path, asked: &str) -> Result<PathBuf> {
    reject_section_address(asked)?;
    if asked.starts_with("sokf:") {
        return resolve_existing(bundle_dir, repo_root, asked);
    }
    if let Ok(existing) = resolve_existing(bundle_dir, repo_root, asked) {
        return Ok(existing);
    }
    let path = physical_path(bundle_dir, repo_root, asked)?;
    if path
        .file_name()
        .is_some_and(|name| name == "manifest.sokf.yaml")
    {
        return sokf_error("mutation of `manifest.sokf.yaml` is reserved");
    }
    if path.extension().is_none_or(|extension| extension != "md") {
        return sokf_error("new SOKF concepts must use a `.md` physical path");
    }
    contained(bundle_dir, &path)
}

fn physical_path(bundle_dir: &Path, repo_root: &Path, asked: &str) -> Result<PathBuf> {
    let asked = Path::new(asked);
    if asked
        .components()
        .any(|part| matches!(part, Component::ParentDir))
    {
        return sokf_error("SOKF target paths must not contain `..`");
    }
    let bundle_relative = bundle_dir.strip_prefix(repo_root).unwrap_or(bundle_dir);
    let path = if asked.is_absolute() {
        asked.to_path_buf()
    } else if asked.starts_with(bundle_relative) {
        repo_root.join(asked)
    } else {
        bundle_dir.join(asked)
    };
    Ok(path)
}

fn contained(bundle_dir: &Path, path: &Path) -> Result<PathBuf> {
    let root = fs::canonicalize(bundle_dir).map_err(|source| Error::Io {
        path: bundle_dir.to_path_buf(),
        source,
    })?;
    let resolved = resolve_nearest(path).ok_or_else(|| Error::Sokf {
        message: format!("cannot safely resolve `{}`", path.display()),
    })?;
    if !resolved.starts_with(&root) {
        return sokf_error(format!(
            "refusing to mutate outside the SOKF knowledge at {}",
            bundle_dir.display()
        ));
    }
    let relative = path.strip_prefix(bundle_dir).map_err(|_| Error::Sokf {
        message: format!(
            "target `{}` is not under the knowledge path",
            path.display()
        ),
    })?;
    let mut here = bundle_dir.to_path_buf();
    for part in relative.components() {
        here.push(part);
        match fs::symlink_metadata(&here) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return sokf_error(format!(
                    "refusing to mutate through symlink `{}`",
                    here.display()
                ));
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => break,
            Err(source) => {
                return Err(Error::Io { path: here, source });
            }
        }
    }
    Ok(path.to_path_buf())
}

fn resolve_nearest(path: &Path) -> Option<PathBuf> {
    if let Ok(exact) = fs::canonicalize(path) {
        return Some(exact);
    }
    let mut tail = Vec::new();
    let mut here = path.to_path_buf();
    let base = loop {
        if let Ok(base) = fs::canonicalize(&here) {
            break base;
        }
        tail.push(here.file_name()?.to_owned());
        if !here.pop() {
            return None;
        }
    };
    let mut resolved = base;
    for part in tail.iter().rev() {
        resolved.push(part);
    }
    Some(resolved)
}

fn reject_section_address(asked: &str) -> Result<()> {
    if asked.starts_with("sokf:") && asked.contains('#') {
        return sokf_error("section-qualified SOKF addresses cannot be mutated");
    }
    Ok(())
}

fn apply_exact_edits(original: &str, edits: &[ExactEdit]) -> Result<String> {
    // Pi matches in an LF-normalised view and restores the file's original
    // line ending and BOM after replacement. Keep that transport behaviour,
    // while deliberately retaining strict exact matching (no fuzzy fallback).
    let (bom, body) = original
        .strip_prefix('\u{feff}')
        .map_or(("", original), |body| ("\u{feff}", body));
    let ending = if body
        .find("\r\n")
        .is_some_and(|crlf| body.find('\n').is_none_or(|newline| crlf < newline + 1))
    {
        "\r\n"
    } else {
        "\n"
    };
    let normalized = normalize_newlines(body);
    let normalized_edits: Vec<(String, String)> = edits
        .iter()
        .map(|edit| {
            (
                normalize_newlines(&edit.old_text),
                normalize_newlines(&edit.new_text),
            )
        })
        .collect();
    let mut located = Vec::with_capacity(edits.len());
    for (old_text, new_text) in &normalized_edits {
        if old_text.is_empty() {
            return sokf_error("oldText must not be empty");
        }
        let matches: Vec<usize> = normalized
            .match_indices(old_text)
            .map(|(offset, _)| offset)
            .collect();
        if matches.len() != 1 {
            return sokf_error(format!(
                "oldText must match exactly once in the original file; found {} matches",
                matches.len()
            ));
        }
        located.push((matches[0], matches[0] + old_text.len(), new_text));
    }
    located.sort_by_key(|(start, _, _)| *start);
    if located.windows(2).any(|pair| pair[0].1 > pair[1].0) {
        return sokf_error("edits overlap in the original file");
    }
    let mut output = normalized;
    for (start, end, new_text) in located.into_iter().rev() {
        output.replace_range(start..end, new_text);
    }
    let output = if ending == "\r\n" {
        output.replace('\n', "\r\n")
    } else {
        output
    };
    Ok(format!("{bom}{output}"))
}

fn normalize_newlines(text: &str) -> String {
    text.replace("\r\n", "\n").replace('\r', "\n")
}

fn check_policy(
    original: Option<&str>,
    replacement: &str,
    policy: MutationPolicy,
    reserved_index: bool,
) -> Result<()> {
    // Indexes are reserved Markdown navigation files, not concepts; they have
    // no frontmatter and therefore no restricted or stamped fields.
    if reserved_index {
        return Ok(());
    }
    let replacement_concept =
        parse_concept("target.md", replacement).map_err(|error| Error::Sokf {
            message: format!("cannot enforce mutation policy: {}", error.message),
        })?;
    if replacement_concept.raw.get("generated").is_some() {
        return sokf_error("stamped field `generated` is not allowed in the working tree");
    }
    if policy == MutationPolicy::HumanOverride {
        return Ok(());
    }
    let old_concept = original
        .map(|text| parse_concept("target.md", text))
        .transpose()
        .map_err(|error| Error::Sokf {
            message: format!("cannot enforce mutation policy: {}", error.message),
        })?;
    if let Some(old_concept) = &old_concept
        && old_concept.id.as_deref() != replacement_concept.id.as_deref()
    {
        return sokf_error("agent-safe mutations must preserve `id`");
    }
    let old_verified = original.and_then(|text| frontmatter_field(text, "verified"));
    let new_verified = frontmatter_field(replacement, "verified");
    let old_has_verified = old_concept
        .as_ref()
        .is_some_and(|concept| concept.raw.get("verified").is_some());
    let new_has_verified = replacement_concept.raw.get("verified").is_some();
    if old_has_verified != old_verified.is_some() || new_has_verified != new_verified.is_some() {
        return sokf_error("cannot locate `verified` bytes safely");
    }
    if old_verified != new_verified {
        return sokf_error("agent-safe mutations must preserve `verified` byte-for-byte");
    }
    Ok(())
}

fn frontmatter_field<'a>(text: &'a str, field: &str) -> Option<&'a str> {
    let mut offset = 0;
    let mut started = false;
    let mut field_start = None;
    for line in text.split_inclusive('\n') {
        let bare = line.trim_end_matches(['\r', '\n']);
        if !started {
            if bare == "---" {
                started = true;
            }
            offset += line.len();
            continue;
        }
        if bare == "---" {
            return field_start.map(|start| &text[start..offset]);
        }
        let key = (!bare.starts_with(char::is_whitespace))
            .then(|| bare.split_once(':').map(|(key, _)| key))
            .flatten()
            .filter(|key| !key.is_empty())
            .map(|key| key.trim_matches(['\'', '"']));
        if let Some(key) = key {
            if let Some(start) = field_start {
                return Some(&text[start..offset]);
            }
            if key == field {
                field_start = Some(offset);
            }
        }
        offset += line.len();
    }
    None
}

fn atomic_write(path: &Path, content: &str) -> Result<()> {
    let parent = path.parent().ok_or_else(|| Error::Sokf {
        message: format!("target `{}` has no parent directory", path.display()),
    })?;
    fs::create_dir_all(parent).map_err(|source| Error::Io {
        path: parent.to_path_buf(),
        source,
    })?;
    let existing_permissions = fs::metadata(path)
        .ok()
        .map(|metadata| metadata.permissions());
    let mut temporary = tempfile::NamedTempFile::new_in(parent).map_err(|source| Error::Io {
        path: parent.to_path_buf(),
        source,
    })?;
    temporary
        .write_all(content.as_bytes())
        .and_then(|()| temporary.as_file().sync_all())
        .map_err(|source| Error::Io {
            path: path.to_path_buf(),
            source,
        })?;
    #[cfg(unix)]
    let desired_permissions = {
        use std::os::unix::fs::PermissionsExt as _;
        existing_permissions.or(Some(fs::Permissions::from_mode(0o644)))
    };
    #[cfg(not(unix))]
    let desired_permissions = existing_permissions;
    if let Some(permissions) = desired_permissions {
        temporary
            .as_file()
            .set_permissions(permissions)
            .map_err(|source| Error::Io {
                path: path.to_path_buf(),
                source,
            })?;
    }
    temporary.persist(path).map_err(|error| Error::Io {
        path: path.to_path_buf(),
        source: error.error,
    })?;
    Ok(())
}

fn snapshot(root: &Path, repo_root: &Path) -> Result<BTreeMap<String, String>> {
    fn visit(repo_root: &Path, dir: &Path, files: &mut BTreeMap<String, String>) -> Result<()> {
        for entry in fs::read_dir(dir).map_err(|source| Error::Io {
            path: dir.to_path_buf(),
            source,
        })? {
            let entry = entry.map_err(|source| Error::Io {
                path: dir.to_path_buf(),
                source,
            })?;
            let kind = entry.file_type().map_err(|source| Error::Io {
                path: entry.path(),
                source,
            })?;
            if kind.is_symlink() {
                continue;
            }
            if kind.is_dir() {
                visit(repo_root, &entry.path(), files)?;
            } else if kind.is_file() {
                let path = entry.path();
                if path.extension().is_none_or(|extension| {
                    extension != "md" && extension != "yaml" && extension != "yml"
                }) {
                    continue;
                }
                files.insert(display_path(repo_root, &path), read(&path)?);
            }
        }
        Ok(())
    }
    let mut files = BTreeMap::new();
    visit(repo_root, root, &mut files)?;
    Ok(files)
}

fn changes_between(
    before: &BTreeMap<String, String>,
    after: &BTreeMap<String, String>,
    source: ChangeSource,
) -> Vec<MutationChange> {
    let paths: BTreeSet<&String> = before.keys().chain(after.keys()).collect();
    paths
        .into_iter()
        .filter_map(|path| {
            let old = before.get(path).map_or("", String::as_str);
            let new = after.get(path).map_or("", String::as_str);
            (old != new).then(|| MutationChange {
                path: path.clone(),
                source,
                diff: whole_file_diff(path, old, new),
            })
        })
        .collect()
}

fn whole_file_diff(path: &str, old: &str, new: &str) -> String {
    let old_lines: Vec<&str> = old.lines().collect();
    let new_lines: Vec<&str> = new.lines().collect();
    let mut diff = format!(
        "--- a/{path}\n+++ b/{path}\n@@ -1,{} +1,{} @@\n",
        old_lines.len(),
        new_lines.len()
    );
    for line in old_lines {
        diff.push('-');
        diff.push_str(line);
        diff.push('\n');
    }
    for line in new_lines {
        diff.push('+');
        diff.push_str(line);
        diff.push('\n');
    }
    diff
}

fn repaired_path(repo_root: &Path, resolved: &str, written: &[String]) -> String {
    for entry in written {
        if let Some((from, to)) = entry.split_once(" -> ")
            && from == resolved
        {
            return to.to_string();
        }
    }
    display_path(repo_root, &repo_root.join(resolved))
}

fn display_path(repo_root: &Path, path: &Path) -> String {
    path.strip_prefix(repo_root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

fn is_reserved_index(path: &Path) -> bool {
    path.file_name().is_some_and(|name| name == "index.md")
}

fn read(path: &Path) -> Result<String> {
    fs::read_to_string(path).map_err(|source| Error::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn sokf_error<T>(message: impl Into<String>) -> Result<T> {
    Err(Error::Sokf {
        message: message.into(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn machine_requests_carry_no_policy_override() {
        let request = r#"{
            "path":"sokf:alpha",
            "edits":[{"oldText":"a","newText":"b"}],
            "allowRestricted":true
        }"#;
        assert!(serde_json::from_str::<EditRequest>(request).is_err());
    }

    #[test]
    fn exact_edits_are_atomic_against_one_original() {
        let edits = vec![
            ExactEdit {
                old_text: "alpha".into(),
                new_text: "A".into(),
            },
            ExactEdit {
                old_text: "gamma".into(),
                new_text: "G".into(),
            },
        ];
        assert_eq!(
            apply_exact_edits("alpha beta gamma", &edits).unwrap(),
            "A beta G"
        );
        assert!(apply_exact_edits("alpha alpha", &edits[..1]).is_err());
    }

    #[test]
    fn exact_edits_preserve_bom_and_crlf_like_the_coding_tool() {
        let original = "\u{feff}one\r\ntwo\r\n";
        let edits = [ExactEdit {
            old_text: "one\ntwo".into(),
            new_text: "ONE\nTWO".into(),
        }];
        assert_eq!(
            apply_exact_edits(original, &edits).unwrap(),
            "\u{feff}ONE\r\nTWO\r\n"
        );
    }

    #[test]
    fn overlapping_edits_are_refused() {
        let edits = vec![
            ExactEdit {
                old_text: "alpha beta".into(),
                new_text: "x".into(),
            },
            ExactEdit {
                old_text: "beta gamma".into(),
                new_text: "y".into(),
            },
        ];
        assert!(apply_exact_edits("alpha beta gamma", &edits).is_err());
    }

    fn repo_with(concept: &str) -> tempfile::TempDir {
        let repo = tempfile::tempdir().unwrap();
        let knowledge = repo.path().join("knowledge");
        fs::create_dir(&knowledge).unwrap();
        fs::write(
            knowledge.join("manifest.sokf.yaml"),
            "sokf: \"0.1\"\nname: test\n",
        )
        .unwrap();
        fs::write(knowledge.join("a.md"), concept).unwrap();
        repo
    }

    #[test]
    fn a_service_edit_repairs_validates_and_reports_the_diff() {
        let original = "---\ntype: T\nid: alpha\n---\nOld body.\n";
        let repo = repo_with(original);
        let result = edit(
            &repo.path().join("knowledge"),
            repo.path(),
            EditRequest {
                path: "sokf:alpha".into(),
                edits: vec![ExactEdit {
                    old_text: "Old body.".into(),
                    new_text: "New body.".into(),
                }],
            },
            MutationPolicy::AgentSafe,
        )
        .unwrap();
        assert_eq!(result.validation, ValidationState::Valid);
        assert_eq!(result.resolved_path, "knowledge/a.md");
        assert_eq!(result.final_path, "knowledge/a.md");
        assert_eq!(result.changes.len(), 1);
        assert_eq!(result.changes[0].source, ChangeSource::Requested);
        assert_eq!(result.changes[0].path, "knowledge/a.md");
        assert!(result.changes[0].diff.contains("-Old body."));
        assert!(result.changes[0].diff.contains("+New body."));
    }

    #[test]
    fn requested_and_automatic_repair_diffs_stay_distinct() {
        let original =
            "---\ntype: T\nid: alpha\nlinks:\n  - rel: depends-on\n    to: beta\n---\nOld.\n";
        let repo = repo_with(original);
        fs::write(
            repo.path().join("knowledge/beta.md"),
            "---\ntype: T\nid: beta\n---\nBeta.\n",
        )
        .unwrap();
        let result = edit(
            &repo.path().join("knowledge"),
            repo.path(),
            EditRequest {
                path: "alpha".into(),
                edits: vec![ExactEdit {
                    old_text: "Old.".into(),
                    new_text: "See [beta](beta.md).".into(),
                }],
            },
            MutationPolicy::AgentSafe,
        )
        .unwrap();
        assert_eq!(result.validation, ValidationState::Valid);
        assert!(result.changes.iter().any(|change| {
            change.source == ChangeSource::Requested && change.path == "knowledge/a.md"
        }));
        assert!(result.changes.iter().any(|change| {
            change.source == ChangeSource::Repair
                && change.path == "knowledge/a.md"
                && change.diff.contains("[beta][sokf:beta]")
        }));
    }

    #[test]
    fn an_applied_invalid_write_is_a_result_not_an_error() {
        let repo = repo_with("---\ntype: T\nid: alpha\n---\na\n");
        let content =
            "---\ntype: T\nid: broken\nlinks:\n  - rel: depends-on\n    to: missing\n---\nb\n";
        let result = write(
            &repo.path().join("knowledge"),
            repo.path(),
            WriteRequest {
                path: "knowledge/broken.md".into(),
                content: content.into(),
            },
            MutationPolicy::AgentSafe,
        )
        .unwrap();
        assert!(result.applied);
        assert_eq!(result.validation, ValidationState::Invalid);
        assert!(
            result.findings.iter().any(|finding| {
                finding.severity == "error" && finding.message.contains("missing")
            })
        );
        assert!(repo.path().join("knowledge/broken.md").is_file());
    }

    #[test]
    fn a_failed_edit_leaves_the_target_byte_identical() {
        let original = "---\ntype: T\nid: alpha\n---\nsame same\n";
        let repo = repo_with(original);
        let result = edit(
            &repo.path().join("knowledge"),
            repo.path(),
            EditRequest {
                path: "alpha".into(),
                edits: vec![ExactEdit {
                    old_text: "same".into(),
                    new_text: "changed".into(),
                }],
            },
            MutationPolicy::AgentSafe,
        );
        assert!(result.is_err());
        assert_eq!(
            fs::read_to_string(repo.path().join("knowledge/a.md")).unwrap(),
            original
        );
    }

    #[test]
    fn agent_safe_write_can_create_an_id_but_not_verification() {
        let repo = repo_with("---\ntype: T\nid: alpha\n---\na\n");
        let knowledge = repo.path().join("knowledge");
        let content = "---\ntype: T\nid: beta\n---\nb\n";
        let result = write(
            &knowledge,
            repo.path(),
            WriteRequest {
                path: "knowledge/b.md".into(),
                content: content.into(),
            },
            MutationPolicy::AgentSafe,
        )
        .unwrap();
        assert_eq!(result.validation, ValidationState::Valid);
        assert_eq!(fs::read_to_string(knowledge.join("b.md")).unwrap(), content);

        let verified = content.replace(
            "id: beta",
            "id: gamma\nverified: { by: human:a, at: 2026-01-01T00:00:00Z }",
        );
        assert!(
            write(
                &knowledge,
                repo.path(),
                WriteRequest {
                    path: "knowledge/c.md".into(),
                    content: verified,
                },
                MutationPolicy::AgentSafe,
            )
            .is_err()
        );
        assert!(!knowledge.join("c.md").exists());
    }

    #[test]
    fn an_absolute_physical_path_can_create_a_concept() {
        let repo = repo_with("---\ntype: T\nid: alpha\n---\na\n");
        let destination = repo.path().join("knowledge/absolute.md");
        let result = write(
            &repo.path().join("knowledge"),
            repo.path(),
            WriteRequest {
                path: destination.display().to_string(),
                content: "---\ntype: T\nid: absolute\n---\nx\n".into(),
            },
            MutationPolicy::AgentSafe,
        )
        .unwrap();
        assert_eq!(result.final_path, "knowledge/absolute.md");
        assert!(destination.is_file());
    }

    #[cfg(unix)]
    #[test]
    fn writes_refuse_symlink_escapes_without_touching_the_destination() {
        use std::os::unix::fs::symlink;

        let repo = repo_with("---\ntype: T\nid: alpha\n---\na\n");
        let outside = tempfile::tempdir().unwrap();
        let destination = outside.path().join("outside.md");
        fs::write(&destination, "outside\n").unwrap();
        symlink(&destination, repo.path().join("knowledge/link.md")).unwrap();
        let result = write(
            &repo.path().join("knowledge"),
            repo.path(),
            WriteRequest {
                path: "knowledge/link.md".into(),
                content: "---\ntype: T\nid: escaped\n---\nx\n".into(),
            },
            MutationPolicy::AgentSafe,
        );
        assert!(result.is_err());
        assert_eq!(fs::read_to_string(destination).unwrap(), "outside\n");
        assert!(repo.path().join("knowledge/link.md").is_symlink());
    }

    #[test]
    fn human_override_allows_identity_but_never_stamped_fields() {
        let old = "---\ntype: T\nid: alpha\n---\na\n";
        let changed = old.replace("id: alpha", "id: beta");
        check_policy(Some(old), &changed, MutationPolicy::HumanOverride, false).unwrap();
        assert!(
            check_policy(
                Some(old),
                &changed.replace("id: beta", "id: beta\ngenerated: { by: export, at: now }"),
                MutationPolicy::HumanOverride,
                false,
            )
            .is_err()
        );
    }

    #[test]
    fn agent_policy_preserves_identity_and_verification_bytes() {
        let old = "---\ntype: Module\nid: one\nverified:\n  by: human:a\n  at: 2026-01-01T00:00:00Z\n---\nold\n";
        let body = old.replace("old", "new");
        check_policy(Some(old), &body, MutationPolicy::AgentSafe, false).unwrap();
        assert!(
            check_policy(
                Some(old),
                &body.replace("id: one", "id: two"),
                MutationPolicy::AgentSafe,
                false,
            )
            .is_err()
        );
        assert!(
            check_policy(
                Some(old),
                &body.replace("by: human:a", "by: human:b"),
                MutationPolicy::AgentSafe,
                false,
            )
            .is_err()
        );
    }
}
