//! content/snapshot.rs — the pack compiled into this binary.

use super::item::Item;
use super::layout;
use super::set::{ContentSet, Origin};

/// Every file of the embedded pack, as (pack-relative path, content).
///
/// Generated by `build.rs` from `assets/`, which is `/pack` through a symlink
/// (ADR-006), so a file added to the pack reaches the binary without a Rust
/// edit. The contents are `include_str!` literals, exactly as a hand-written
/// table would put them there.
pub(crate) const FILES: &[(&str, &str)] = include!(concat!(env!("OUT_DIR"), "/pack_files.rs"));

/// The embedded pack's items, read by the same layout rules a fetched pack
/// takes — snapshot and pack are one code path, not two.
pub(crate) fn items() -> Vec<Item> {
    layout::items_from(FILES.iter().copied())
}

/// The embedded pack's own `pack.toml`, verbatim.
pub fn pack_manifest_source() -> &'static str {
    FILES
        .iter()
        .find(|(path, _)| *path == "pack.toml")
        .expect("the embedded pack carries a pack.toml")
        .1
}

/// The content a run has before any pack is resolved: layer 0.
pub fn snapshot() -> ContentSet {
    ContentSet::from_layer(items(), Origin::Snapshot)
}

/// The snapshot, built once per test process.
///
/// Every test wants the same set, and a `Ctx` needs to borrow one that
/// outlives it; a `OnceLock` gives both without a binding at each site.
#[cfg(test)]
pub(crate) fn test_snapshot() -> &'static ContentSet {
    static SET: std::sync::OnceLock<ContentSet> = std::sync::OnceLock::new();
    SET.get_or_init(snapshot)
}

#[cfg(test)]
mod tests {
    //! What the embedded pack must carry.
    //!
    //! The components now read this set rather than hand-written tables, so
    //! a parity assertion against those tables would compare the set with
    //! itself. What is worth pinning instead is the shape: every kind is
    //! populated, the exceptions stay out, and the project templates — which
    //! still keep their own tables — match file for file.

    use super::*;
    use crate::capability::Capability;
    use crate::components::sokf;
    use crate::content::item::{ItemKind, Owner};

    fn knowledge() -> Owner {
        Owner::Knowledge
    }

    /// A rule that stops matching would empty a kind silently, and every
    /// component reading it would plan nothing at all.
    #[test]
    fn every_kind_is_populated() {
        let set = snapshot();
        for (owner, kind, least) in [
            (knowledge(), ItemKind::Skill, 15),
            (knowledge(), ItemKind::KnowledgeSkeleton, 20),
            (knowledge(), ItemKind::DocTemplate, 40),
            (Owner::Capability(Capability::Skills), ItemKind::Skill, 2),
            (Owner::Repo, ItemKind::AgentScaffold, 3),
            (Owner::Repo, ItemKind::ProjectTemplate, 2),
        ] {
            let found = set.items_of(owner, kind).count();
            assert!(
                found >= least,
                "{owner:?}/{kind:?}: {found} items, expected at least {least}"
            );
        }
    }

    /// The names the rules produce, spot-checked against each pattern: a
    /// `<name>.md` kind drops the extension, `concepts/<name>` keeps it.
    #[test]
    fn items_are_named_as_their_pattern_spells_it() {
        let set = snapshot();
        assert!(set.item(knowledge(), ItemKind::Skill, "frame").is_some());
        assert!(
            set.item(knowledge(), ItemKind::DocTemplate, "adr")
                .is_some()
        );
        assert!(
            set.item(knowledge(), ItemKind::DocTemplate, "adr.md")
                .is_none()
        );
        assert!(
            set.item(Owner::Repo, ItemKind::AgentScaffold, "coding")
                .is_some()
        );
        assert!(
            set.item(
                knowledge(),
                ItemKind::KnowledgeSkeleton,
                "manifest.sokf.yaml"
            )
            .is_some(),
            "a concept entry keeps its extension"
        );
        let plans = set
            .item(knowledge(), ItemKind::KnowledgeSkeleton, "plans")
            .expect("a concept directory is one item");
        assert_eq!(plans.files.len(), 1, "and holds its whole subtree");
    }

    /// The project templates are the one kind still driven by a table, so
    /// this is a real cross-check rather than the set against itself.
    #[test]
    fn every_project_template_reaches_the_snapshot() {
        let set = snapshot();
        let in_set: Vec<&str> = set
            .items_of(Owner::Repo, ItemKind::ProjectTemplate)
            .map(|i| i.name.as_str())
            .collect();
        let mut shipped: Vec<&str> = crate::templates::shipped().iter().map(|t| t.name).collect();
        shipped.sort();
        assert_eq!(in_set, shipped);

        // The template table restores tokenised segments in the *target*
        // path, so the pack path and the target path differ by design; what
        // must match is the content, file for file.
        for template in crate::templates::shipped() {
            let item = set
                .item(Owner::Repo, ItemKind::ProjectTemplate, template.name)
                .expect("present");
            let mut expected: Vec<&str> = template.files.iter().map(|(_, c)| *c).collect();
            expected.sort();
            let mut found: Vec<&str> = item.files.iter().map(|(_, c)| c.as_str()).collect();
            found.sort();
            assert_eq!(
                found, expected,
                "{}: every file, byte for byte",
                template.name
            );
        }
    }

    /// The instruction files and the AOKF spec ship from the pack tree but
    /// are not content: they describe a version the binary pins or a format
    /// the compiled validator enforces. `pack.toml` is metadata.
    #[test]
    fn what_is_not_content_stays_out_of_the_snapshot() {
        let files: usize = items().iter().map(|i| i.files.len()).sum();
        let not_content = sokf::binary_owned_count() + 2 /* codegraph, rtk */ + 1 /* pack.toml */;
        assert_eq!(
            files + not_content,
            FILES.len(),
            "every file in the pack is content or a named exception"
        );
    }
}
