//! content/snapshot.rs — the pack compiled into this binary.

use super::item::Item;
use super::layout;
use super::set::{ContentSet, Origin};

/// Every file of the embedded pack, as (pack-relative path, content).
///
/// Generated by `build.rs` from `assets/`, which is `/pack` through a symlink
/// (ADR-006), so a file added to the pack reaches the binary without a Rust
/// edit. The contents are `include_str!` literals, exactly as a hand-written
/// table would put them there.
pub(crate) const FILES: &[(&str, &str)] = include!(concat!(env!("OUT_DIR"), "/pack_files.rs"));

/// The embedded pack's items, read by the same layout rules a fetched pack
/// takes — snapshot and pack are one code path, not two.
pub(crate) fn items() -> Vec<Item> {
    layout::items_from(FILES.iter().copied())
}

/// The content a run has before any pack is resolved: layer 0.
pub fn snapshot() -> ContentSet {
    ContentSet::from_layer(items(), Origin::Snapshot)
}

#[cfg(test)]
mod tests {
    //! Parity with the components.
    //!
    //! Nothing reads the snapshot yet, so these tests are what keeps it
    //! honest: every asset a component ships today must reach the snapshot as
    //! an item, byte for byte. When the components start reading `ContentSet`
    //! they inherit a set already proven equal to what they write now.

    use std::collections::BTreeMap;

    use super::*;
    use crate::action::Ownership;
    use crate::capability::Capability;
    use crate::components::{aokf, aokf_skills, skillpack};
    use crate::content::item::{ItemKind, Owner};

    fn knowledge() -> Owner {
        Owner::Capability(Capability::Knowledge)
    }

    fn set() -> ContentSet {
        snapshot()
    }

    /// The one file of a single-file item.
    fn only_file<'a>(set: &'a ContentSet, owner: Owner, kind: ItemKind, name: &str) -> &'a str {
        let item = set
            .item(owner, kind, name)
            .unwrap_or_else(|| panic!("snapshot carries {name:?} as {kind:?}"));
        assert_eq!(item.files.len(), 1, "{name} is a single-file item");
        assert_eq!(item.files[0].0, "", "a single-file item's path is empty");
        &item.files[0].1
    }

    #[test]
    fn every_knowledge_carried_skill_reaches_the_snapshot() {
        let set = set();
        let shipped: BTreeMap<&str, &[(&str, &str)]> =
            aokf_skills::SKILLS.iter().map(|(n, f)| (*n, *f)).collect();
        let in_set: Vec<&str> = set
            .items_of(knowledge(), ItemKind::Skill)
            .map(|i| i.name.as_str())
            .collect();
        assert_eq!(
            in_set,
            shipped.keys().copied().collect::<Vec<_>>(),
            "the same skills, by name"
        );
        for (name, files) in &shipped {
            let item = set
                .item(knowledge(), ItemKind::Skill, name)
                .expect("present");
            let mut expected: Vec<(String, String)> = files
                .iter()
                .map(|(rel, content)| ((*rel).to_string(), (*content).to_string()))
                .collect();
            expected.sort();
            assert_eq!(item.files, expected, "{name}: every file, byte for byte");
        }
    }

    #[test]
    fn every_skill_pack_skill_reaches_the_snapshot() {
        let set = set();
        let owner = Owner::Capability(Capability::Skills);
        let in_set: Vec<&str> = set
            .items_of(owner, ItemKind::Skill)
            .map(|i| i.name.as_str())
            .collect();
        let shipped: Vec<&str> = skillpack::SKILLS.iter().map(|(n, _)| *n).collect();
        assert_eq!(in_set, shipped);
        for (name, content) in skillpack::SKILLS {
            let item = set.item(owner, ItemKind::Skill, name).expect("present");
            assert_eq!(
                item.files,
                [("SKILL.md".to_string(), content.to_string())],
                "{name}: byte for byte"
            );
        }
    }

    #[test]
    fn every_bundle_scaffold_reaches_the_snapshot() {
        let set = set();
        // A scaffold's target is `knowledge/` plus its path under
        // `concepts/`, so the item is named by the first segment after it.
        let shipped: Vec<(&str, &str)> = aokf::FILES
            .iter()
            .filter(|(_, _, ownership, _)| matches!(ownership, Ownership::Scaffold))
            .map(|(target, content, _, _)| {
                let rest = target.strip_prefix("knowledge/").expect("bundle scaffold");
                (rest, *content)
            })
            .collect();
        assert_eq!(shipped.len(), 25, "the scaffold set this pins");

        for (rest, content) in &shipped {
            let (name, rel) = match rest.split_once('/') {
                Some((dir, under)) => (dir, under),
                None => (*rest, ""),
            };
            let item = set
                .item(knowledge(), ItemKind::KnowledgeSkeleton, name)
                .unwrap_or_else(|| panic!("snapshot carries the {name} scaffold"));
            let found = item
                .files
                .iter()
                .find(|(path, _)| path == rel)
                .unwrap_or_else(|| panic!("{name} carries {rel:?}"));
            assert_eq!(&found.1, content, "knowledge/{rest}: byte for byte");
        }

        // No item the components do not ship, and none of them twice.
        let file_count: usize = set
            .items_of(knowledge(), ItemKind::KnowledgeSkeleton)
            .map(|i| i.files.len())
            .sum();
        assert_eq!(file_count, shipped.len(), "no scaffold the components lack");
    }

    #[test]
    fn every_document_template_reaches_the_snapshot() {
        let set = set();
        let in_set: Vec<&str> = set
            .items_of(knowledge(), ItemKind::DocTemplate)
            .map(|i| i.name.as_str())
            .collect();
        // The shipped table keys on the file name; the item is named by the
        // `<name>.md` pattern, so without the extension.
        let mut shipped: Vec<&str> = aokf::TEMPLATE_FILES
            .iter()
            .map(|(file, _)| file.strip_suffix(".md").expect("templates are Markdown"))
            .collect();
        shipped.sort();
        assert_eq!(in_set, shipped);
        for (file, content) in aokf::TEMPLATE_FILES {
            let name = file.strip_suffix(".md").expect("templates are Markdown");
            assert_eq!(
                only_file(&set, knowledge(), ItemKind::DocTemplate, name),
                *content,
                "{file}: byte for byte"
            );
        }
    }

    #[test]
    fn every_general_rules_scaffold_reaches_the_snapshot() {
        let set = set();
        for (target, content) in crate::pipeline::RULE_SCAFFOLDS {
            let name = target
                .strip_prefix(".agents/")
                .and_then(|file| file.strip_suffix(".md"))
                .expect("agent scaffold");
            assert_eq!(
                only_file(&set, Owner::Repo, ItemKind::AgentScaffold, name),
                content,
                "{target}: byte for byte"
            );
        }
        assert_eq!(
            set.items_of(Owner::Repo, ItemKind::AgentScaffold).count(),
            crate::pipeline::RULE_SCAFFOLDS.len(),
            "the capability instruction files are not scaffolds and must not appear"
        );
    }

    #[test]
    fn every_project_template_reaches_the_snapshot() {
        let set = set();
        let in_set: Vec<&str> = set
            .items_of(Owner::Repo, ItemKind::ProjectTemplate)
            .map(|i| i.name.as_str())
            .collect();
        let mut shipped: Vec<&str> = crate::templates::shipped().iter().map(|t| t.name).collect();
        shipped.sort();
        assert_eq!(in_set, shipped);

        // The template table restores tokenised segments in the *target*
        // path, so the pack path and the target path differ by design; what
        // must match is the content, file for file.
        for template in crate::templates::shipped() {
            let item = set
                .item(Owner::Repo, ItemKind::ProjectTemplate, template.name)
                .expect("present");
            let mut expected: Vec<&str> = template.files.iter().map(|(_, c)| *c).collect();
            expected.sort();
            let mut found: Vec<&str> = item.files.iter().map(|(_, c)| c.as_str()).collect();
            found.sort();
            assert_eq!(
                found, expected,
                "{}: every file, byte for byte",
                template.name
            );
        }
    }

    /// The instruction files and the AOKF spec ship from the pack tree but are
    /// not content: they describe a version the binary pins or a format the
    /// compiled validator enforces. `pack.toml` is metadata.
    #[test]
    fn what_is_not_content_stays_out_of_the_snapshot() {
        let files: usize = items().iter().map(|i| i.files.len()).sum();
        let owned_by_the_binary = aokf::FILES
            .iter()
            .filter(|(_, _, ownership, _)| matches!(ownership, Ownership::Owned))
            .count();
        assert_eq!(owned_by_the_binary, 2, "the instructions and the AOKF spec");
        // Every pack file is either an item's or one of the four the binary
        // owns, plus pack.toml itself.
        let not_content = owned_by_the_binary + 2 /* codegraph, rtk */ + 1 /* pack.toml */;
        assert_eq!(
            files + not_content,
            FILES.len(),
            "every file in the pack is content or a named exception"
        );
    }
}
